# Makefile

CC=gcc
CFLAGS = -isysroot /Developer/SDKs/MacOSX10.5.sdk -mmacosx-version-min=10.5



all: build

build: Makefile slip2udp.c
	$(CC) -o slip2udp slip2udp.c

clean:
	rm -f slip2udp.o core
